### ISSUE TITLE
Faraday::ParsingError when creating a post

### ISSUE THREAD

**Issue by abmartinr** [dblock/slack-ruby-client#100] opened 2016-07-25 08:51 UTC
Hey! 

We have an app that automatically will create a Slack Post in an specific thread. It has been working fine so far but "2 Sundays in a row" it has failed with the following message and I can't seem to find the root cause for it. 

This is the error:

```
2016-07-24T08:02:43.020424+00:00 app[web.1]: [c97e8948-5e3e-4524-c5d6-b8ca3a6bbce0]
2016-07-24T08:02:43.020432+00:00 app[web.1]: Faraday::ParsingError (757: unexpected token at 'Array
2016-07-24T08:02:43.020434+00:00 app[web.1]: (
2016-07-24T08:02:43.020435+00:00 app[web.1]:     [ok] =>
2016-07-24T08:02:43.020436+00:00 app[web.1]:     [error] => read_failed
2016-07-24T08:02:43.020436+00:00 app[web.1]:     [stack] => Array
2016-07-24T08:02:43.020437+00:00 app[web.1]:         (
2016-07-24T08:02:43.020452+00:00 app[web.1]:                 (
2016-07-24T08:02:43.020453+00:00 app[web.1]:                     [0] => bad_socket_key
2016-07-24T08:02:43.020453+00:00 app[web.1]:                     [1] => ds38:10443
2016-07-24T08:02:43.020454+00:00 app[web.1]:                 )
2016-07-24T08:02:43.020455+00:00 app[web.1]:
2016-07-24T08:02:43.020451+00:00 app[web.1]:             [0] => Array
2016-07-24T08:02:43.020457+00:00 app[web.1]:                     [1] => only read 0 / 1 bytes
2016-07-24T08:02:43.020456+00:00 app[web.1]:                     [0] => short_read
2016-07-24T08:02:43.020458+00:00 app[web.1]:                 )
2016-07-24T08:02:43.020458+00:00 app[web.1]:
2016-07-24T08:02:43.020456+00:00 app[web.1]:                 (
2016-07-24T08:02:43.020455+00:00 app[web.1]:             [1] => Array
2016-07-24T08:02:43.020460+00:00 app[web.1]:                     [0] => eof_during
2016-07-24T08:02:43.020459+00:00 app[web.1]:                 (
2016-07-24T08:02:43.020459+00:00 app[web.1]:             [2] => Array
2016-07-24T08:02:43.020461+00:00 app[web.1]:                     [1] => eof:
2016-07-24T08:02:43.020461+00:00 app[web.1]:                 )
2016-07-24T08:02:43.020462+00:00 app[web.1]:             [3] => Array
2016-07-24T08:02:43.020464+00:00 app[web.1]:                     [0] => meta
2016-07-24T08:02:43.020463+00:00 app[web.1]:                 (
2016-07-24T08:02:43.020462+00:00 app[web.1]:
2016-07-24T08:02:43.020465+00:00 app[web.1]:                     [1] => {"stream_type":"tcp_socket\/ssl","mode":"r+","unread_bytes":0,"seekable":false,"timed_out":true,"blocked":true,"eof":false}
2016-07-24T08:02:43.020466+00:00 app[web.1]:                 )
2016-07-24T08:02:43.020467+00:00 app[web.1]:
2016-07-24T08:02:43.020467+00:00 app[web.1]:             [4] => Array
2016-07-24T08:02:43.020468+00:00 app[web.1]:                 (
2016-07-24T08:02:43.020468+00:00 app[web.1]:                     [0] => missing_len
2016-07-24T08:02:43.020469+00:00 app[web.1]:                     [1] => failed to read length for string
2016-07-24T08:02:43.020470+00:00 app[web.1]:
2016-07-24T08:02:43.020471+00:00 app[web.1]:         )
2016-07-24T08:02:43.020469+00:00 app[web.1]:                 )
2016-07-24T08:02:43.020471+00:00 app[web.1]:
2016-07-24T08:02:43.020473+00:00 app[web.1]: {"ok":false,"error":"markdown_conversion_failed"}'):
2016-07-24T08:02:43.020472+00:00 app[web.1]: )
2016-07-24T08:02:43.020473+00:00 app[web.1]:   app/services/slack_service.rb:108:in `create_post'
2016-07-24T08:02:43.020474+00:00 app[web.1]:   app/models/incident.rb:54:in `notify_channels'
2016-07-24T08:02:43.020475+00:00 app[web.1]:   app/controllers/api/incidents_controller.rb:23:in `create'
2016-07-24T08:02:43.020476+00:00 app[web.1]:
2016-07-24T08:02:43.015219+00:00 heroku[router]: at=info method=POST path="/api/incidents/create.json" host=zdredalert.herokuapp.com request_id=c97e8948-5e3e-4524-c5d6-b8ca3a6bbce0 fwd="194.72.81.34,192.161.152.148" dyno=web.1 connect=1ms service=3481ms status=500 bytes=215
2016-07-24T08:02:43.020476+00:00 app[web.1]:
```

The problem comes from here: 

```
 file = @client.files_upload(
      channels: ENV["SLACK_CHANNEL"],
      as_user: true,
      filetype: "post",
      content: get_template("start_slack_content",content_par),
      title: get_template("start_slack_subject",subject_par),
      filename: "red_alert_#{incident.ticket_id}",
      initial_comment: 'Red Alert has been created.'
    )
```

That's the line failing. What I've never seen is both errors that are being returned there:

`Faraday::ParsingError (757: unexpected token at 'Array`
`{"ok":false,"error":"markdown_conversion_failed"}'):`

Any ideas?

Thanks!

**Comment by dblock** [comment] 2016-07-25 11:51
Looks like an error coming from Slack that's sending you some garbage with the JSON that includes `markdown_conversion_failed`. The parser fails to parse that and spews the error.

I would try to reproduce on a simple command line, then open a ticket with them. The server should never return malformed JSON.

The error itself seems to say that your `content` is not valid markdown.

**Comment by abmartinr** [comment] 2016-07-25 12:29
Thanks for the quick reply @dblock . I haven't been able to reproduce it at all but will try to contact slack and see if they have some more information. Will update this when I get more info.

**Comment by abmartinr** [comment] 2016-07-27 16:13
It turns out to be an issue on Slack side. There is a bug related to Post creation, which occurs sporadically when using the API.  They are working on it. :)

**Comment by dblock** [comment] 2016-07-27 18:24
I am going to close this here, thanks!

**Closed by dblock** 2016-07-27 18:24 UTC
Labels: bug?
